version: '3.8'

services:
  synology-telegram-downloader:
    image: ghcr.io/leolionart/synology-telegram-downloader:latest
    container_name: synology-telegram-downloader
    restart: always
    env_file:
      - .env
    volumes:
      # Thay đường dẫn bên trái bằng đường dẫn tuyệt đối thư mục NAS của bạn
      # Ví dụ: /volumeUSB1/usbshare/Movies:/downloads
      - /volumeUSB1/usbshare/Movies:/downloads
